version: '3.8'

x-logging: &default-logging
  driver: json-file
  options:
    max-size: 100m
    max-file: 100

networks:
  docker-network:
    driver: bridge

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${PORT}:3000'
    environment:
      - DB_HOST=postgres_db
      - DB_PORT=5432
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - postgres_db
    networks:
      - docker-network
    logging: *default-logging

  postgres_db:
    image: bitnami/postgresql:latest
    platform: linux/amd64
    ports:
      - '${DB_PORT}:5432'
    restart: always
    volumes:
      - db-data:/bitnami/postgresql
    environment:
      - POSTGRESQL_DATABASE=${DB_NAME}
      - POSTGRESQL_USERNAME=${DB_USER}
      - POSTGRESQL_PASSWORD=${DB_PASSWORD}
    networks:
      - docker-network
    logging: *default-logging

volumes:
  db-data:
